apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels: # these labels belong to deployment
    app: rabbitmq
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: rabbitmq
      tier: db
      project: roboshop
  template: # this is the pod definition
    metadata:
      labels:
        app: rabbitmq
        tier: db
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
    tier: db
    project: roboshop
  ports:
    - name: name-of-service-port
      port: 6379
      protocol: TCP
      targetPort: 6379


