apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels: # these labels belong to deployment
    app: user
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: user
      tier: db
      project: roboshop
  template: # this is the pod definition
    metadata:
      labels:
        app: user
        tier: db
        project: roboshop
    spec:
      containers:
      - name: user
        image: iamnr/user:1.0.0
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
    tier: db
    project: roboshop
  ports:
    - name: name-of-service-port
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: user
  namespace: roboshop
data: 
  MONGO: "true" # keep true in double quotes
  MONGO_URL: "mongodb://mongodb:27017/user"  # protocol//service-name:service-port/schema
  REDIS_HOST: "redis"


